services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio123;
      /usr/bin/mc rb --force local/${AWS_STORAGE_BUCKET_NAME}/;
      /usr/bin/mc mb --quiet local/${AWS_STORAGE_BUCKET_NAME}/;
      /usr/bin/mc policy set public local/${AWS_STORAGE_BUCKET_NAME};
      "
    depends_on:
      - minio

volumes:
  minio-data: