services:
  ninetofiver:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE?}
      - DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION?}
      - CFG_FILE_PATH=${CFG_FILE_PATH?}
      - MYSQL_DB=${MYSQL_DATABASE?}
      - MYSQL_USER=${MYSQL_USER?}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE?}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED?}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL?}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME?}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD?}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT?}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER?}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD?}
      - MINIO_MEDIA_FILES_BUCKET=${MINIO_BUCKET?}
    command: > 
      bash -c "
          python manage.py migrate &&
          echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('${SUPERUSER_USERNAME?}', '${SUPERUSER_EMAIL?}', '${SUPERUSER_PASSWORD?}')\" | python manage.py shell || true &&
          echo \"from oauth2_provider.models import Application; from django.contrib.auth import get_user_model; User = get_user_model(); client = Application.objects.create(user=User.objects.filter(is_staff=True)[0], name='${API_APPLICATION_NAME?}', client_id='${API_APPLICATION_CLIENT_ID?}', client_secret='${API_APPLICATION_CLIENT_SECRET?}', authorization_grant_type=Application.GRANT_PASSWORD)\" | python manage.py shell || true &&
          python manage.py runserver 0.0.0.0:8000"
    networks:
      - ninetofiver
    ports:
      - "8000:8000"

  minio:
    image: minio/minio:latest
    hostname: "minio"
    command: 'minio server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - ninetofiver

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio $MINIO_URL $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do sleep 10; done &&
      mc mb --ignore-existing myminio/$MINIO_BUCKET &&
      mc anonymous set public myminio/$MINIO_BUCKET &&
      mc admin user add myminio $MINIO_USER $MINIO_PASSWORD &&
      mc admin policy attach myminio readwrite --user=$MINIO_USER &&
      mc admin user svcacct add myminio $MINIO_USER --access-key=$MINIO_SVC_ACCESS_KEY --secret-key=$MINIO_SVC_SECRET_KEY"
    env_file:
      - .env
    networks:
      - ninetofiver



  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - ninetofiver
      - minio
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ninetofiver
      - MYSQL_USER=ninetofiver
      - MYSQL_PASSWORD=ninetofiver
      - MINIO_ENDPOINT:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio-client
      - MINIO_MEDIA_FILES_BUCKET=media
    volumes:
      - ./media:/scripts/migrate_to_minio/media
    networks:
      - ninetofiver

volumes:
  minio-data:

networks:
  ninetofiver:
