services: 
  minio:
    image: minio/minio:latest
    hostname: "minio"
    command: 'minio server /miniodata --console-address ":9001"'
    env_file: 
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
