# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-11 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ninetofiver', '0088_auto_20190709_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_users',
            field=models.ManyToManyField(through='ninetofiver.ContractUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
