# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0090_auto_20190722_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=9),
        ),
    ]
