# Generated by Django 3.2 on 2021-05-04 09:19

from django.db import migrations, models
import django.db.models.deletion
import ninetofiver.models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0091_auto_20190730_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperformance',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'permissions': (('receive_modified_attachment_notification', 'Can receive modified attachment notifications'),)},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='consultancycontract',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractestimate',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractgroup',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractlog',
            options={'base_manager_name': 'objects', 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='contractlogtype',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='contractrole',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractuser',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractusergroup',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractuserworkschedule',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employmentcontract',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employmentcontracttype',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'permissions': (('receive_pending_leave_reminder', 'Can receive pending leave reminders'),)},
        ),
        migrations.AlterModelOptions(
            name='leavedate',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'base_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'base_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='performancetype',
            options={'base_manager_name': 'objects', 'ordering': ['multiplier']},
        ),
        migrations.AlterModelOptions(
            name='projectcontract',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='standbyperformance',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='supportcontract',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'base_manager_name': 'objects', 'ordering': ['-ends_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'verbose_name_plural': 'user info'},
        ),
        migrations.AlterModelOptions(
            name='userrelative',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usertraining',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='whereabout',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelManagers(
            name='activityperformance',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='apikey',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='attachment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='consultancycontract',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contract',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractestimate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractgroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractlog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractlogtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractrole',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractusergroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contractuserworkschedule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='employmentcontract',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='employmentcontracttype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='holiday',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='leave',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='leavedate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='leavetype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='performance',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='performancetype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='projectcontract',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='standbyperformance',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='supportcontract',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='timesheet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='training',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='trainingtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userrelative',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usertraining',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='whereabout',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='workschedule',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(limit_choices_to=ninetofiver.models.Contract.company_choices, on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.company'),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='company',
            field=models.ForeignKey(limit_choices_to=ninetofiver.models.EmploymentContract.company_choices, on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.company'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='overtime',
            field=models.BooleanField(default=False, verbose_name='Overtime compensation'),
        ),
    ]
