# Generated by Django 4.0 on 2023-05-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0093_performanceinuitskrk_alter_apikey_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'permissions': (('receive_bday_anniversary_reminder', 'Can receive birthday and anniversary reminders'),), 'verbose_name_plural': 'user info'},
        ),
    ]
