# Generated by Django 4.0 on 2024-02-04 04:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0094_alter_userinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
